
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestaoclientes-v1
  labels:
    app: gestaoclientes
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestaoclientes
      version: v1
  template:
    metadata:
      labels:
        app: gestaoclientes
        version: v1
    spec:
      serviceAccountName: oauth0-gestao-clientes
      containers:
        - name: gestaoclientes
          image: docker.io/lyamane/gestaoclientes:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3200
---